name: Build and Package THJInstaller

on:
  workflow_dispatch:
    inputs:
      branch:
        default: ossign
        type: choice
        description: The branch to build from
        options:
          - ossign
          - main
          - master
        required: true
  push:
    branches: 
      - ossign

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
          
      - name: Get version from .csproj
        id: get_version
        shell: pwsh
        run: |
          Out-File -FilePath $env:GITHUB_ENV -Append -InputObject "VERSION=$($([xml]$(Get-Content .\THJPatcher.csproj)).Project.PropertyGroup.Version)"
      
      - name: Replace URL to signed patcher and add options for single-file installer creation
        shell: pwsh
        run: |
          (Get-Content -Path .\Helpers\SteamHelper.cs).
          replace('github.com/The-Heroes-Journey-EQEMU/thj-patcher', 'github.com/ossign/the-heroes-journey-eqemu--thj-patcher') | 
          Set-Content -Path .\Helpers\SteamHelper.cs
          
          (Get-Content -Path .\THJPatcher.csproj).
          replace('</Version>', @"
          </Version>
              <PublishSingleFile>true</PublishSingleFile>
              <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
              <DebugType>embedded</DebugType>
          "@).
          replace('<None Update="steam_appid.txt">', '<None Update="steam_appid.txt" Pack="true" PackagePath="/">') | 
          Set-Content -Path .\THJPatcher.csproj

      - name: Restore and build
        run: |
          dotnet build -c Release -o build .\THJPatcher.csproj
          if (-not (Test-Path -Path build\*.exe)) { throw "No compiled file found in output directory!" }
      
      - name: Sign DLLs and executables
        uses: azure/trusted-signing-action@v0
        with:
          azure-tenant-id: ${{ secrets.ATS_TENANT_ID }}
          azure-client-id: ${{ secrets.ATS_LIVE_CLIENT_ID }}
          azure-client-secret: ${{ secrets.ATS_LIVE_CLIENT_SECRET }}
          endpoint: ${{ secrets.ATS_ENDPOINT }}
          trusted-signing-account-name: ${{ secrets.ATS_ACCOUNT_NAME }}
          certificate-profile-name: ${{ secrets.ATS_LIVE_PROFILE_NAME }}
          files-folder: ./build
          files-folder-filter: exe,dll
          file-digest: ${{ vars.ATS_DIGEST }}
          timestamp-rfc3161: ${{ vars.ATS_TIMESTAMP }}
          timestamp-digest: ${{ vars.ATS_DIGEST }}
          description-url: ${{ vars.ATS_DESCRIPTION_URL }}
      
      - name: Create installer
        shell: pwsh
        run: dotnet publish -c Release -o dist --no-build --artifacts-path .\build .\THJPatcher.csproj
      
      - name: Sign installer
        uses: azure/trusted-signing-action@v0
        with:
          azure-tenant-id: ${{ secrets.ATS_TENANT_ID }}
          azure-client-id: ${{ secrets.ATS_LIVE_CLIENT_ID }}
          azure-client-secret: ${{ secrets.ATS_LIVE_CLIENT_SECRET }}
          endpoint: ${{ secrets.ATS_ENDPOINT }}
          trusted-signing-account-name: ${{ secrets.ATS_ACCOUNT_NAME }}
          certificate-profile-name: ${{ secrets.ATS_LIVE_PROFILE_NAME }}
          files-folder: ./dist
          files-folder-filter: exe
          file-digest: ${{ vars.ATS_DIGEST }}
          timestamp-rfc3161: ${{ vars.ATS_TIMESTAMP }}
          timestamp-digest: ${{ vars.ATS_DIGEST }}
          description-url: ${{ vars.ATS_DESCRIPTION_URL }}

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          files: dist/*.exe
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}